apiVersion: route.openshift.io/v1
kind: Route
metadata: { name: frontend }
spec:
  to: { kind: Service, name: frontend }
  port: { targetPort: 3000 }
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: api
spec:
  path: /api
  to: { kind: Service, name: api }
  port: { targetPort: 8080 }
